# Metrics
[settings.metrics]
send-metrics = false
service-checks = ["apiserver", "chronyd", "containerd", "host-containerd", "docker"]

# Network
[metadata.settings.network]
affected-services = ["bootstrap-containers", "containerd", "docker", "host-containerd", "host-containers", "updog"]
