[workspace]
resolver = "1"
members = [
    "packages/settings-defaults",
    "packages/settings-plugins",

    "variants/aws-dev",
    "variants/aws-ecs-2",
    "variants/aws-ecs-2-fips",
    "variants/aws-ecs-2-nvidia",
    "variants/aws-ecs-2-nvidia-fips",
    "variants/aws-ecs-3",
    "variants/aws-ecs-3-fips",
    "variants/aws-ecs-3-nvidia",
    "variants/aws-ecs-3-nvidia-fips",
    "variants/aws-ecs-4",
    "variants/aws-ecs-4-nvidia",
    "variants/aws-mantle-1",
    "variants/aws-mantle-1-fips",
    "variants/aws-mantle-1-nvidia",
    "variants/aws-mantle-1-nvidia-fips",
    "variants/aws-k8s-1.31",
    "variants/aws-k8s-1.31-fips",
    "variants/aws-k8s-1.32",
    "variants/aws-k8s-1.32-fips",
    "variants/aws-k8s-1.33",
    "variants/aws-k8s-1.33-fips",
    "variants/aws-k8s-1.34",
    "variants/aws-k8s-1.34-fips",
    "variants/aws-k8s-1.35",
    "variants/aws-k8s-1.35-fips",
    "variants/aws-k8s-1.36",
    "variants/aws-k8s-1.36-fips",
    "variants/aws-k8s-1.31-nvidia",
    "variants/aws-k8s-1.31-nvidia-fips",
    "variants/aws-k8s-1.32-nvidia",
    "variants/aws-k8s-1.32-nvidia-fips",
    "variants/aws-k8s-1.33-nvidia",
    "variants/aws-k8s-1.33-nvidia-fips",
    "variants/aws-k8s-1.34-nvidia",
    "variants/aws-k8s-1.34-nvidia-fips",
    "variants/aws-k8s-1.35-nvidia",
    "variants/aws-k8s-1.35-nvidia-fips",
    "variants/aws-k8s-1.36-nvidia",
    "variants/aws-k8s-1.36-nvidia-fips",
    "variants/metal-dev",
    "variants/vmware-dev",
    "variants/vmware-k8s-1.31",
    "variants/vmware-k8s-1.31-fips",
    "variants/vmware-k8s-1.32",
    "variants/vmware-k8s-1.32-fips",
    "variants/vmware-k8s-1.33",
    "variants/vmware-k8s-1.33-fips",
    "variants/vmware-k8s-1.34",
    "variants/vmware-k8s-1.34-fips",
    "variants/vmware-k8s-1.35",
    "variants/vmware-k8s-1.35-fips",
    "variants/vmware-k8s-1.36",
    "variants/vmware-k8s-1.36-fips",
]

[profile.dev]
debug = false
opt-level = 'z'

[profile.dev.build-override]
opt-level = 'z'
