schema-version = 2
release-version = "1.58.0"
project-vendor = "Bottlerocket"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.72.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "5.3.2"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "14.0.0"
vendor = "bottlerocket"
