schema-version = 2
release-version = "1.61.0"
project-vendor = "Bottlerocket"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.74.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "5.6.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "14.4.0"
vendor = "bottlerocket"
