%global _cross_first_party 1
%undefine _debugsource_packages

Name: %{_cross_os}pluto
Version: 0.0
Release: 0%{?dist}
Summary: Dynamic setting generator for kubernetes
License: Apache-2.0 OR MIT
URL: https://github.com/bottlerocket-os/bottlerocket

# Generated by https://github.com/aws/amazon-vpc-cni-k8s/blob/master/scripts/gen_vpc_ip_limits.go
Source0: eni-max-pods

BuildRequires: %{_cross_os}glibc-devel

%description
%{summary}.

%build
echo "** Building pluto:"
%cargo_build --manifest-path %{_builddir}/sources/Cargo.toml \
    -p pluto

%install
install -d %{buildroot}%{_cross_bindir}
install -p -m 0755 ${HOME}/.cache/%{__cargo_target}/release/pluto %{buildroot}%{_cross_bindir}

install -d %{buildroot}%{_cross_datadir}/eks
install -p -m 0644 %{S:0} %{buildroot}%{_cross_datadir}/eks

%files
%{_cross_bindir}/pluto
%dir %{_cross_datadir}/eks
%{_cross_datadir}/eks/eni-max-pods
