/*
 * Thar, the API
 *
 * The API for Thar, the OS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;

use super::configuration::Configuration;

use super::default_api;

pub struct APIClient {
    configuration: Rc<Configuration>,
    default_api: Box<default_api::DefaultApi>,
}

impl APIClient {
    pub fn new(configuration: Configuration) -> APIClient {
        let rc = Rc::new(configuration);

        APIClient {
            configuration: rc.clone(),
            default_api: Box::new(default_api::DefaultApiClient::new(rc.clone())),
        }
    }

    pub fn default_api(&self) -> &default_api::DefaultApi{
        self.default_api.as_ref()
    }

}
