/*
 * Thar, the API
 *
 * The API for Thar, the OS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


pub struct Configuration {
    pub base_path: String,
    pub client: reqwest::Client,
}

impl Configuration {
    pub fn new() -> Configuration {
        Configuration::default()
    }
}

impl Default for Configuration {
    fn default() -> Self {
        Configuration {
            base_path: "http://localhost:4242".to_owned(),
            client: reqwest::Client::new(),
        }
    }
}
