# Container runtime - image verification
[services.image-verification]
configuration-files = [
  "containerd-image-verifiers-toml",
  "thar-be-image-verifiers-toml",
]
restart-commands = ["/usr/bin/thar-be-image-verifiers"]

[metadata.settings.image-verifier-plugins]
affected-services = ["image-verification"]

# Reload the containerd configuration drop-in
[metadata.settings.image-verifier-plugins.enabled]
affected-services = ["containerd", "image-verification"]

[configuration-files.containerd-image-verifiers-toml]
path = "/etc/containerd/config.d/002-image-verification-plugins.toml"
template-path = "/usr/share/templates/containerd-image-verifiers-toml"

[configuration-files.thar-be-image-verifiers-toml]
path = "/etc/thar-be-image-verifiers.toml"
template-path = "/usr/share/templates/thar-be-image-verifiers-toml"
