# Updates settings.

[settings.updates]
version-lock = "latest"
ignore-waves = false

[services.thar-be-updates]
configuration-files = ["thar-be-updates-toml"]
restart-commands = []

[services.updog]
configuration-files = ["updog-toml"]
restart-commands = []

[configuration-files.thar-be-updates-toml]
path = "/etc/thar-be-updates.toml"
template-path = "/usr/share/templates/thar-be-updates-toml"

[configuration-files.updog-toml]
path = "/etc/updog.toml"
template-path = "/usr/share/templates/updog-toml"

[metadata.settings.updates]
affected-services = ["updog", "thar-be-updates"]
seed.setting-generator = "bork seed"

# Updog config has proxy servers and needs to be regenerated if those network
# settings change.

[metadata.settings.network]
affected-services = ["containerd", "host-containerd", "host-containers", "updog"]
