#!/usr/bin/env sh
#
# environment-setup - setup shell for building in
#
if [ -d "${INFRA_DIR:-./tools/infra}/env/bin" ]; then
    PATH="$(pwd -P)/tools/infra/env/bin:$PATH"
fi

for src_path in $(env | awk -F'=' '/^CODEBUILD_SRC_DIR/ { print $2; }'); do
    for src_bin in "$src_path/bin" "$src_path/ci/bin"; do
        if [ -d "$src_bin" ]; then
            PATH="$src_bin:$PATH"
        fi
    done
done
