#!/usr/bin/env bash
#
# install-rust - install rust for use in builder containers
#
# usage:
#
#   install-rust
#

install_rust_toolchain() {
    local toolchain="${1:-stable}"
    test -f rustup-init.sh || rm -f rustup-init.sh
    if ! curl -o rustup-init.sh --proto '=https' --tlsv1.2 -sS "https://sh.rustup.rs"; then
        logger -s -t ERROR "could not fetch rustup, needed for managing rust toolchain"
        exit 1
    fi
    if ! bash rustup-init.sh -y --profile minimal --no-modify-path --default-toolchain "$toolchain" ; then
        logger -s -t ERROR "could not setup rustup & rust toolchain for build"
        exit 1
    fi
    rm -f rustup-init.sh
}

install_rust_toolchain "stable"
