#!/usr/bin/env bash
#
# install-crates - install binary crate dependencies
#
# usage:
#
#   install-rust
#

cargo_dep() {
    cargo_install_package="$@"
    logger -s -t INFO "installing cargo dep with 'cargo install $cargo_install_package'"
    if ! cargo install --force $cargo_install_package; then
        logger -s -t ERROR "failed to install dep with 'cargo install $cargo_install_package'"
        exit 1
    fi
}

# Install build tooling dependencies
cargo_dep --version 0.23.0 cargo-make
cargo_dep --version 0.2.6  cargo-deny

